import React from 'react';

export default function EnvironmentalAnalysis({ analysis }) {
  if (!analysis) return null;

  return (
    <div className="ai-analysis mt-6 p-6 rounded-2xl bg-primary/10 border border-primary/20 shadow-lg animate-in fade-in slide-in-from-top-4 duration-500">
      <div className="flex items-center gap-3 mb-4">
        <div className="p-2 rounded-lg bg-primary text-background-dark">
          <span className="material-symbols-outlined text-xl">auto_awesome</span>
        </div>
        <h3 className="text-lg font-bold text-primary">AI Environmental Insight</h3>
      </div>
      <div className="prose prose-sm dark:prose-invert max-w-none">
        <p className="text-sm leading-relaxed text-slate-700 dark:text-slate-300 whitespace-pre-wrap">
          {analysis}
        </p>
      </div>
      <div className="mt-4 flex items-center gap-2">
        <span className="flex h-2 w-2 rounded-full bg-primary animate-pulse"></span>
        <span className="text-[10px] font-bold uppercase tracking-widest text-primary/60">Generated by Gemini 1.5 Flash</span>
      </div>
    </div>
  );
}
